
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControleService", targetNamespace = "http://ServidorSOAP/", wsdlLocation = "http://localhost/soap/?WSDL")
public class ControleService
    extends Service
{

    private final static URL CONTROLESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLESERVICE_EXCEPTION;
    private final static QName CONTROLESERVICE_QNAME = new QName("http://ServidorSOAP/", "ControleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/soap/?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLESERVICE_WSDL_LOCATION = url;
        CONTROLESERVICE_EXCEPTION = e;
    }

    public ControleService() {
        super(__getWsdlLocation(), CONTROLESERVICE_QNAME);
    }

    public ControleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLESERVICE_QNAME, features);
    }

    public ControleService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLESERVICE_QNAME);
    }

    public ControleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLESERVICE_QNAME, features);
    }

    public ControleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Controle
     */
    @WebEndpoint(name = "ControlePort")
    public Controle getControlePort() {
        return super.getPort(new QName("http://ServidorSOAP/", "ControlePort"), Controle.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Controle
     */
    @WebEndpoint(name = "ControlePort")
    public Controle getControlePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServidorSOAP/", "ControlePort"), Controle.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLESERVICE_EXCEPTION!= null) {
            throw CONTROLESERVICE_EXCEPTION;
        }
        return CONTROLESERVICE_WSDL_LOCATION;
    }

}
