
package proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Controle", targetNamespace = "http://ServidorSOAP/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Controle {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServidorSOAP/Controle/alterarRequest", output = "http://ServidorSOAP/Controle/alterarResponse")
    public boolean alterar(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServidorSOAP/Controle/adicionarRequest", output = "http://ServidorSOAP/Controle/adicionarResponse")
    public boolean adicionar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServidorSOAP/Controle/excluirRequest", output = "http://ServidorSOAP/Controle/excluirResponse")
    public boolean excluir(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servidorsoap.FraseArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServidorSOAP/Controle/listaTipoRequest", output = "http://ServidorSOAP/Controle/listaTipoResponse")
    public FraseArray listaTipo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servidorsoap.Frase
     */
    @WebMethod(operationName = "Consultar")
    @WebResult(partName = "return")
    @Action(input = "http://ServidorSOAP/Controle/ConsultarRequest", output = "http://ServidorSOAP/Controle/ConsultarResponse")
    public Frase consultar(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servidorsoap.Frase
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ServidorSOAP/Controle/mensagemAleatoriaRequest", output = "http://ServidorSOAP/Controle/mensagemAleatoriaResponse")
    public Frase mensagemAleatoria(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
